pipeline {
    agent any

    environment {
        IMAGE_NAME = "pythonapp"
        CONTAINER_NAME = "pythonapp"
//	SONAR_HOST_URL = "http://localhost:9000"   

 }

    stages {
        stage ('Git checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/dom-sag/CICDProject.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
            
                // Use the SonarQube server configured in Jenkins
                  withSonarQubeEnv('SonarQube-Local') { 
                  '''
                  sh 
                      sonar-scanner \
                      -Dsonar.projectKey=sonar-project \
                      -Dsonar.sources=.
                    '''
		}	
	    }			
	}
   }

	stage('Quality Gate') {
            	steps {
                	timeout(time: 10, unit: 'MINUTES') {
                    	waitForQualityGate abortPipeline: true
                }
            }
        }

	stage ('Build the docker image') {
            steps {
                  dir('pythonproject') {
                  sh 'pwd'
                  sh 'ls -ltr'
                  sh "docker build -t ${IMAGE_NAME}:latest ."
                }
            }
        
     }
        stage ('Run Container') {
            steps {
                
                 sh "docker run -d -p 5000:5000 --name ${CONTAINER_NAME} ${IMAGE_NAME}:latest"
                }
            }
        }
    }
    
